import core.fields
import dirtyfields.dirtyfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyImportBatch',
            fields=[
                ('id', models.UUIDField(db_column='UUID', default=None, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', null=True)),
                ('date_created', core.fields.DateTimeField(db_column='DateCreated', null=True)),
                ('date_updated', core.fields.DateTimeField(db_column='DateUpdated', null=True)),
                ('version', models.IntegerField(default=1)),
                ('code', models.CharField(blank=True, max_length=64, null=True)),
                ('source_system', models.CharField(default='PSSN', max_length=64)),
                ('household_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('member_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In progress'), ('SUCCESS', 'Success'), ('COMPLETED_WITH_ERRORS', 'Completed with errors'), ('FAIL', 'Fail')], default='PENDING', max_length=32)),
                ('started_at', core.fields.DateTimeField(blank=True, null=True)),
                ('finished_at', core.fields.DateTimeField(blank=True, null=True)),
                ('total_households', models.IntegerField(default=0)),
                ('total_members', models.IntegerField(default=0)),
                ('success_household_count', models.IntegerField(default=0)),
                ('success_member_count', models.IntegerField(default=0)),
                ('warning_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('error', models.JSONField(blank=True, default=dict)),
                ('user_created', models.ForeignKey(db_column='UserCreatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='legacyimportbatch_user_created', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(db_column='UserUpdatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='legacyimportbatch_user_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={'managed': True},
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LegacyGroup',
            fields=[
                ('id', models.UUIDField(db_column='UUID', default=None, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', null=True)),
                ('date_created', core.fields.DateTimeField(db_column='DateCreated', null=True)),
                ('date_updated', core.fields.DateTimeField(db_column='DateUpdated', null=True)),
                ('version', models.IntegerField(default=1)),
                ('code', models.CharField(max_length=20)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='legacy_groups', to='legacy_individual.legacyimportbatch')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='legacy_groups', to='location.location')),
                ('user_created', models.ForeignKey(db_column='UserCreatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='legacygroup_user_created', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(db_column='UserUpdatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='legacygroup_user_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={'managed': True},
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LegacyIndividual',
            fields=[
                ('id', models.UUIDField(db_column='UUID', default=None, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', null=True)),
                ('date_created', core.fields.DateTimeField(db_column='DateCreated', null=True)),
                ('date_updated', core.fields.DateTimeField(db_column='DateUpdated', null=True)),
                ('version', models.IntegerField(default=1)),
                ('legacy_code', models.CharField(max_length=32)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255)),
                ('dob', core.fields.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('disability', models.BooleanField(blank=True, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=32, null=True)),
                ('nin', models.CharField(blank=True, max_length=32, null=True)),
                ('premno', models.CharField(blank=True, max_length=32, null=True)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='legacy_individuals', to='legacy_individual.legacyimportbatch')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='legacy_individuals', to='location.location')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='legacy_individuals', to='location.healthfacility')),
                ('user_created', models.ForeignKey(db_column='UserCreatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='legacyindividual_user_created', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(db_column='UserUpdatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='legacyindividual_user_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={'managed': True},
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LegacyGroupIndividual',
            fields=[
                ('id', models.UUIDField(db_column='UUID', default=None, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', null=True)),
                ('date_created', core.fields.DateTimeField(db_column='DateCreated', null=True)),
                ('date_updated', core.fields.DateTimeField(db_column='DateUpdated', null=True)),
                ('version', models.IntegerField(default=1)),
                ('role', models.CharField(blank=True, choices=[('HEAD', 'HEAD'), ('SPOUSE', 'SPOUSE'), ('SON', 'SON'), ('DAUGHTER', 'DAUGHTER'), ('FATHER', 'FATHER'), ('MOTHER', 'MOTHER'), ('BROTHER', 'BROTHER'), ('SISTER', 'SISTER'), ('GRANDSON', 'GRANDSON'), ('GRANDDAUGHTER', 'GRANDDAUGHTER'), ('GRANDFATHER', 'GRANDFATHER'), ('GRANDMOTHER', 'GRANDMOTHER'), ('OTHER RELATIVE', 'OTHER RELATIVE'), ('NOT RELATED', 'NOT RELATED')], max_length=32, null=True)),
                ('relationship_code', models.CharField(blank=True, max_length=8, null=True)),
                ('recipient_type', models.CharField(blank=True, choices=[('PRIMARY', 'PRIMARY'), ('SECONDARY', 'SECONDARY')], max_length=16, null=True)),
                ('member_line', models.IntegerField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='memberships', to='legacy_individual.legacygroup')),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='memberships', to='legacy_individual.legacyindividual')),
                ('user_created', models.ForeignKey(db_column='UserCreatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='legacygroupindividual_user_created', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(db_column='UserUpdatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='legacygroupindividual_user_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={'managed': True},
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),

        migrations.CreateModel(
            name='HistoricalLegacyImportBatch',
            fields=[
                ('id', models.UUIDField(db_column='UUID', db_index=True, default=None, editable=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', null=True)),
                ('date_created', core.fields.DateTimeField(db_column='DateCreated', null=True)),
                ('date_updated', core.fields.DateTimeField(db_column='DateUpdated', null=True)),
                ('version', models.IntegerField(default=1)),
                ('code', models.CharField(blank=True, max_length=64, null=True)),
                ('source_system', models.CharField(default='PSSN', max_length=64)),
                ('household_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('member_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In progress'), ('SUCCESS', 'Success'), ('COMPLETED_WITH_ERRORS', 'Completed with errors'), ('FAIL', 'Fail')], default='PENDING', max_length=32)),
                ('started_at', core.fields.DateTimeField(blank=True, null=True)),
                ('finished_at', core.fields.DateTimeField(blank=True, null=True)),
                ('total_households', models.IntegerField(default=0)),
                ('total_members', models.IntegerField(default=0)),
                ('success_household_count', models.IntegerField(default=0)),
                ('success_member_count', models.IntegerField(default=0)),
                ('warning_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('error', models.JSONField(blank=True, default=dict)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_created', models.ForeignKey(blank=True, db_column='UserCreatedUUID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, db_column='UserUpdatedUUID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical legacy import batch',
                'verbose_name_plural': 'historical legacy import batches',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalLegacyGroup',
            fields=[
                ('id', models.UUIDField(db_column='UUID', db_index=True, default=None, editable=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', null=True)),
                ('date_created', core.fields.DateTimeField(db_column='DateCreated', null=True)),
                ('date_updated', core.fields.DateTimeField(db_column='DateUpdated', null=True)),
                ('version', models.IntegerField(default=1)),
                ('code', models.CharField(max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('import_batch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='legacy_individual.legacyimportbatch')),
                ('location', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='location.location')),
                ('user_created', models.ForeignKey(blank=True, db_column='UserCreatedUUID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, db_column='UserUpdatedUUID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical legacy group',
                'verbose_name_plural': 'historical legacy groups',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalLegacyIndividual',
            fields=[
                ('id', models.UUIDField(db_column='UUID', db_index=True, default=None, editable=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', null=True)),
                ('date_created', core.fields.DateTimeField(db_column='DateCreated', null=True)),
                ('date_updated', core.fields.DateTimeField(db_column='DateUpdated', null=True)),
                ('version', models.IntegerField(default=1)),
                ('legacy_code', models.CharField(max_length=32)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255)),
                ('dob', core.fields.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('disability', models.BooleanField(blank=True, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=32, null=True)),
                ('nin', models.CharField(blank=True, max_length=32, null=True)),
                ('premno', models.CharField(blank=True, max_length=32, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('import_batch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='legacy_individual.legacyimportbatch')),
                ('location', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='location.location')),
                ('facility', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='location.healthfacility')),
                ('user_created', models.ForeignKey(blank=True, db_column='UserCreatedUUID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, db_column='UserUpdatedUUID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical legacy individual',
                'verbose_name_plural': 'historical legacy individuals',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalLegacyGroupIndividual',
            fields=[
                ('id', models.UUIDField(db_column='UUID', db_index=True, default=None, editable=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', null=True)),
                ('date_created', core.fields.DateTimeField(db_column='DateCreated', null=True)),
                ('date_updated', core.fields.DateTimeField(db_column='DateUpdated', null=True)),
                ('version', models.IntegerField(default=1)),
                ('role', models.CharField(blank=True, choices=[('HEAD', 'HEAD'), ('SPOUSE', 'SPOUSE'), ('SON', 'SON'), ('DAUGHTER', 'DAUGHTER'), ('FATHER', 'FATHER'), ('MOTHER', 'MOTHER'), ('BROTHER', 'BROTHER'), ('SISTER', 'SISTER'), ('GRANDSON', 'GRANDSON'), ('GRANDDAUGHTER', 'GRANDDAUGHTER'), ('GRANDFATHER', 'GRANDFATHER'), ('GRANDMOTHER', 'GRANDMOTHER'), ('OTHER RELATIVE', 'OTHER RELATIVE'), ('NOT RELATED', 'NOT RELATED')], max_length=32, null=True)),
                ('relationship_code', models.CharField(blank=True, max_length=8, null=True)),
                ('recipient_type', models.CharField(blank=True, choices=[('PRIMARY', 'PRIMARY'), ('SECONDARY', 'SECONDARY')], max_length=16, null=True)),
                ('member_line', models.IntegerField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('group', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='legacy_individual.legacygroup')),
                ('individual', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='legacy_individual.legacyindividual')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_created', models.ForeignKey(blank=True, db_column='UserCreatedUUID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, db_column='UserUpdatedUUID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical legacy group individual',
                'verbose_name_plural': 'historical legacy group individuals',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),

        migrations.AddIndex(
            model_name='legacyimportbatch',
            index=models.Index(fields=['code'], name='legacy_imp_code_idx'),
        ),
        migrations.AddIndex(
            model_name='legacyimportbatch',
            index=models.Index(fields=['status'], name='legacy_imp_status_idx'),
        ),
        migrations.AddIndex(
            model_name='legacyimportbatch',
            index=models.Index(fields=['source_system'], name='legacy_imp_source_idx'),
        ),
        migrations.AddIndex(
            model_name='legacyimportbatch',
            index=models.Index(fields=['date_created'], name='legacy_imp_dc_idx'),
        ),

        migrations.AddIndex(
            model_name='legacygroup',
            index=models.Index(fields=['code'], name='legacy_grp_code_idx'),
        ),
        migrations.AddIndex(
            model_name='legacygroup',
            index=models.Index(fields=['location'], name='legacy_grp_loc_idx'),
        ),
        migrations.AddIndex(
            model_name='legacygroup',
            index=models.Index(fields=['import_batch'], name='legacy_grp_batch_idx'),
        ),
        migrations.AddConstraint(
            model_name='legacygroup',
            constraint=models.UniqueConstraint(
                condition=models.Q(('is_deleted', False)),
                fields=('code', 'import_batch'),
                name='legacy_group_code_per_batch_unique',
            ),
        ),

        migrations.AddIndex(
            model_name='legacyindividual',
            index=models.Index(fields=['legacy_code'], name='legacy_ind_code_idx'),
        ),
        migrations.AddIndex(
            model_name='legacyindividual',
            index=models.Index(fields=['premno'], name='legacy_ind_premno_idx'),
        ),
        migrations.AddIndex(
            model_name='legacyindividual',
            index=models.Index(fields=['last_name'], name='legacy_ind_lname_idx'),
        ),
        migrations.AddIndex(
            model_name='legacyindividual',
            index=models.Index(fields=['dob'], name='legacy_ind_dob_idx'),
        ),
        migrations.AddIndex(
            model_name='legacyindividual',
            index=models.Index(fields=['location'], name='legacy_ind_loc_idx'),
        ),
        migrations.AddIndex(
            model_name='legacyindividual',
            index=models.Index(fields=['facility'], name='legacy_ind_fac_idx'),
        ),
        migrations.AddIndex(
            model_name='legacyindividual',
            index=models.Index(fields=['import_batch'], name='legacy_ind_batch_idx'),
        ),
        migrations.AddConstraint(
            model_name='legacyindividual',
            constraint=models.UniqueConstraint(
                condition=models.Q(('is_deleted', False)),
                fields=('legacy_code', 'import_batch'),
                name='legacy_individual_legacycode_per_batch_unique',
            ),
        ),
        migrations.AddConstraint(
            model_name='legacyindividual',
            constraint=models.UniqueConstraint(
                condition=models.Q(('is_deleted', False), models.Q(('nin', None), _negated=True), models.Q(('nin', ''), _negated=True)),
                fields=('nin',),
                name='legacy_individual_nin_unique_when_present',
            ),
        ),

        migrations.AddIndex(
            model_name='legacygroupindividual',
            index=models.Index(fields=['group'], name='legacy_gi_group_idx'),
        ),
        migrations.AddIndex(
            model_name='legacygroupindividual',
            index=models.Index(fields=['individual'], name='legacy_gi_ind_idx'),
        ),
        migrations.AddIndex(
            model_name='legacygroupindividual',
            index=models.Index(fields=['role'], name='legacy_gi_role_idx'),
        ),
        migrations.AddIndex(
            model_name='legacygroupindividual',
            index=models.Index(fields=['relationship_code'], name='legacy_gi_relcode_idx'),
        ),
        migrations.AddIndex(
            model_name='legacygroupindividual',
            index=models.Index(fields=['member_line'], name='legacy_gi_mline_idx'),
        ),
        migrations.AddConstraint(
            model_name='legacygroupindividual',
            constraint=models.UniqueConstraint(
                condition=models.Q(('is_deleted', False)),
                fields=('group', 'individual'),
                name='legacy_groupindividual_active_unique',
            ),
        ),
    ]
