# Generated by Django 4.2.30 on 2026-06-10 11:32

import core.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('legacy_individual', '0002_add_legacy_rights_to_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicallegacyimportbatch',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical legacy import batch', 'verbose_name_plural': 'historical legacy import batchs'},
        ),
        migrations.RenameIndex(
            model_name='legacygroup',
            new_name='legacy_indi_code_375e57_idx',
            old_name='legacy_grp_code_idx',
        ),
        migrations.RenameIndex(
            model_name='legacygroup',
            new_name='legacy_indi_locatio_f14b95_idx',
            old_name='legacy_grp_loc_idx',
        ),
        migrations.RenameIndex(
            model_name='legacygroup',
            new_name='legacy_indi_import__24a21e_idx',
            old_name='legacy_grp_batch_idx',
        ),
        migrations.RenameIndex(
            model_name='legacygroupindividual',
            new_name='legacy_indi_group_i_5d1963_idx',
            old_name='legacy_gi_group_idx',
        ),
        migrations.RenameIndex(
            model_name='legacygroupindividual',
            new_name='legacy_indi_individ_bd0854_idx',
            old_name='legacy_gi_ind_idx',
        ),
        migrations.RenameIndex(
            model_name='legacygroupindividual',
            new_name='legacy_indi_role_2946b7_idx',
            old_name='legacy_gi_role_idx',
        ),
        migrations.RenameIndex(
            model_name='legacygroupindividual',
            new_name='legacy_indi_relatio_0ab8a4_idx',
            old_name='legacy_gi_relcode_idx',
        ),
        migrations.RenameIndex(
            model_name='legacygroupindividual',
            new_name='legacy_indi_member__b08351_idx',
            old_name='legacy_gi_mline_idx',
        ),
        migrations.RenameIndex(
            model_name='legacyimportbatch',
            new_name='legacy_indi_code_c5b3b4_idx',
            old_name='legacy_imp_code_idx',
        ),
        migrations.RenameIndex(
            model_name='legacyimportbatch',
            new_name='legacy_indi_status_f8f160_idx',
            old_name='legacy_imp_status_idx',
        ),
        migrations.RenameIndex(
            model_name='legacyimportbatch',
            new_name='legacy_indi_source__056674_idx',
            old_name='legacy_imp_source_idx',
        ),
        migrations.RenameIndex(
            model_name='legacyimportbatch',
            new_name='legacy_indi_DateCre_e0e730_idx',
            old_name='legacy_imp_dc_idx',
        ),
        migrations.RenameIndex(
            model_name='legacyindividual',
            new_name='legacy_indi_legacy__411510_idx',
            old_name='legacy_ind_code_idx',
        ),
        migrations.RenameIndex(
            model_name='legacyindividual',
            new_name='legacy_indi_premno_4b326c_idx',
            old_name='legacy_ind_premno_idx',
        ),
        migrations.RenameIndex(
            model_name='legacyindividual',
            new_name='legacy_indi_last_na_45fef3_idx',
            old_name='legacy_ind_lname_idx',
        ),
        migrations.RenameIndex(
            model_name='legacyindividual',
            new_name='legacy_indi_dob_42da3c_idx',
            old_name='legacy_ind_dob_idx',
        ),
        migrations.RenameIndex(
            model_name='legacyindividual',
            new_name='legacy_indi_locatio_4c1e11_idx',
            old_name='legacy_ind_loc_idx',
        ),
        migrations.RenameIndex(
            model_name='legacyindividual',
            new_name='legacy_indi_facilit_d12d29_idx',
            old_name='legacy_ind_fac_idx',
        ),
        migrations.RenameIndex(
            model_name='legacyindividual',
            new_name='legacy_indi_import__3caf55_idx',
            old_name='legacy_ind_batch_idx',
        ),
        migrations.AlterField(
            model_name='historicallegacygroup',
            name='date_created',
            field=core.fields.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicallegacygroup',
            name='date_updated',
            field=core.fields.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicallegacygroupindividual',
            name='date_created',
            field=core.fields.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicallegacygroupindividual',
            name='date_updated',
            field=core.fields.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicallegacyimportbatch',
            name='date_created',
            field=core.fields.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicallegacyimportbatch',
            name='date_updated',
            field=core.fields.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicallegacyindividual',
            name='date_created',
            field=core.fields.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicallegacyindividual',
            name='date_updated',
            field=core.fields.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='legacygroup',
            name='date_created',
            field=core.fields.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='legacygroup',
            name='date_updated',
            field=core.fields.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='legacygroup',
            name='user_created',
            field=models.ForeignKey(db_column='UserCreatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='legacygroup',
            name='user_updated',
            field=models.ForeignKey(db_column='UserUpdatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='legacygroupindividual',
            name='date_created',
            field=core.fields.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='legacygroupindividual',
            name='date_updated',
            field=core.fields.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='legacygroupindividual',
            name='user_created',
            field=models.ForeignKey(db_column='UserCreatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='legacygroupindividual',
            name='user_updated',
            field=models.ForeignKey(db_column='UserUpdatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='legacyimportbatch',
            name='date_created',
            field=core.fields.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='legacyimportbatch',
            name='date_updated',
            field=core.fields.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='legacyimportbatch',
            name='user_created',
            field=models.ForeignKey(db_column='UserCreatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='legacyimportbatch',
            name='user_updated',
            field=models.ForeignKey(db_column='UserUpdatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='legacyindividual',
            name='date_created',
            field=core.fields.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='legacyindividual',
            name='date_updated',
            field=core.fields.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='legacyindividual',
            name='user_created',
            field=models.ForeignKey(db_column='UserCreatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='legacyindividual',
            name='user_updated',
            field=models.ForeignKey(db_column='UserUpdatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
