# Generated by Django 4.2.30 on 2026-07-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy_individual', '0003_alter_historicallegacyimportbatch_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallegacyindividual',
            name='first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='historicallegacyindividual',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='legacyindividual',
            name='first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='legacyindividual',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
