# Generated by Django 4.2.30 on 2026-08-12 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0019_alter_location_code'),
        ('legacy_individual', '0006_legacyindividual_first_name_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallegacyimportbatch',
            name='district',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='location.location'),
        ),
        migrations.AddField(
            model_name='historicallegacyimportbatch',
            name='region',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='location.location'),
        ),
        migrations.AddField(
            model_name='legacyimportbatch',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='legacy_import_batches_district', to='location.location'),
        ),
        migrations.AddField(
            model_name='legacyimportbatch',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='legacy_import_batches_region', to='location.location'),
        ),
        migrations.AddIndex(
            model_name='legacyimportbatch',
            index=models.Index(fields=['district'], name='legacy_indi_distric_9895db_idx'),
        ),
        migrations.AddIndex(
            model_name='legacyimportbatch',
            index=models.Index(fields=['region'], name='legacy_indi_region__8b5f81_idx'),
        ),
    ]
