"""Canonical PSSN column vocabulary shared by the CSV workflow and the API adapter.

See docs/LEGACY_API_ETL_CODE_RATIONALE.md.
"""

_HOUSEHOLD_KNOWN_COLUMNS = {
    'REGISTRATIONNO', 'UNIQUENO', 'WAVENO', 'ROUNDNO', 'BATCHNO', 'FORMNO',
    'REGION_CODE', 'DISTRICT_CODE', 'WARD_CODE', 'VILLAGE_CODE',
    'URBANORRULAR', 'AREA_CODE', 'SUBVILLAGE', 'POPULAR_AREA',
    'HH_FIRSTNAME', 'HH_MIDDLENAME', 'HH_LASTNAME',
    'NO_HH_CHANGE', 'NEW_HH_FIRSTNAME', 'NEW_HH_MIDDLENAME', 'NEW_HH_LASTNAME',
    'AGE', 'DOB', 'POPULAR_HH_NAME',
    'HHSTATUS', 'HHSIZE', 'PMTSCORE', 'HHCLASSIFICATION', 'V_STATUS',
    'PHONE_NO', 'BANK_ACCOUNT',
    'EPAYMENT_CODE', 'EPAYMENT_APPROACH', 'EPAYMENT_ACCOUNT',
    'EPAYMENT_BANK_BRANCH', 'EPAYMENT_STATUS', 'EPAYMENT_REGISTERED_NAME',
    'APR_EPAYMENT_CODE', 'APR_EPAYMENT_ACCOUNT', 'APR_EPAYMENT_BANK_BRANCH',
    'APR_EPAYMENT_APPROACH', 'APR_EPAYMENT_REGISTERED_NAME',
    'APRROVED_DATE', 'APPROVED_BY',
    'ENROLLMENT_DATE', 'SIGNED_REPRESENTATIVE', 'SUPERVISOR_NAME',
    'SIGNED_BY_SUPERVISOR', 'DATAENTRYID', 'CAPTUREDBY', 'DATECAPTURED',
    'UPDATEDBY', 'DATEUPDATED', 'APPROVEDBY', 'DATEAPPROVED',
    'REVIEWED_BY', 'REVIEWED_DATE', 'REMARKS',
}

_MEMBER_KNOWN_COLUMNS = {
    'UNIQUENO', 'MEMBERLINENO', 'REGISTRATIONNO', 'REF_UNIQUENO',
    'FIRSTNAME', 'MIDDLENAME', 'LASTNAME',
    'NEW_FIRSTNAME', 'NEW_MIDDLENAME', 'NEW_LASTNAME', 'NO_CHANGE',
    'SEX', 'AGE', 'NEW_AGE', 'GRADE',
    'DATEOFBIRTH', 'NEW_DATEOFBIRTH',
    'DISABILITY', 'DISLEVEL', 'DIS_REASON', 'CHRONICALILINESS',
    'RELATIONSHIPTOHEAD', 'NEW_RELATIONSHIPTOHEAD', 'HH_REP',
    'NIDA_NIN', 'NIDA_FIRSTNAME', 'NIDA_MIDDLENAME', 'NIDA_LASTNAME',
    'NIDA_BIRTH_DATE', 'NIDA_EXPIRY_DATE', 'NIDA_STATUS', 'NO_NIDA_REASON',
    'PREM_NO', 'PREM_STATUS', 'PREM_CODE',
    'FACILITY_CODE', 'FACILITY_NAME',
    'SIS_DOB', 'SIS_SEX', 'SIS_SCHOOL_ID', 'SIS_ID', 'SIS_PHOTO',
    'SIS_SCHOOL_CODE', 'SIS_GRADE', 'SIS_UPDATE_YEAR',
    'SERVICE_CAT', 'HH_MEMBER_STATUS', 'HH_MEMBER_EXEMPTION', 'V_STATUS',
}

_HOUSEHOLD_API_PREFIX = 'HH_'
_MEMBER_API_PREFIX = 'MEMBER_'


def to_household_column(api_key):
    if not isinstance(api_key, str) or api_key.startswith(_MEMBER_API_PREFIX):
        return None
    stripped = (
        api_key[len(_HOUSEHOLD_API_PREFIX):]
        if api_key.startswith(_HOUSEHOLD_API_PREFIX)
        else api_key
    )
    if api_key in _HOUSEHOLD_KNOWN_COLUMNS:
        return api_key
    if stripped in _HOUSEHOLD_KNOWN_COLUMNS:
        return stripped
    return None


def to_member_column(api_key):
    if not isinstance(api_key, str) or not api_key.startswith(_MEMBER_API_PREFIX):
        return None
    stripped = api_key[len(_MEMBER_API_PREFIX):]
    return stripped if stripped in _MEMBER_KNOWN_COLUMNS else None
